<?php
/** @var Dbtours\Calendar\ViewModel\Events\Filter $view */
$view = $block->getViewModel();
?>
<div class="event-filter">
    <label class="admin__field-label">
        <span><b><?= __('Guide') ?></b></span>
    </label>
    <?= $view->getGuideSelect() ?>

    <label class="admin__field-label">
        <span><b><?= __('Event Type') ?></b></span>
    </label>
    <?= $view->getEventTpeSelect()?>
    <button class="search">Filter</button>
</div>

<script>
    require(["jquery"], function($) {
        $("button.search").click(function () {
            var guideId = $("#guide-filter").val();
            var typeId = $("#type-filter").val();
            console.log(guideId);
            console.log(typeId);
            search(guideId, typeId);
        });
    });
</script>



<style type="text/css">
    .event-filter {
        margin-bottom:30px
    }
    .event-filter .admin__field-label span {
        margin-bottom:10px
    }
    .event-filter .admin__control-select {
        margin-right:30px
    }
</style>


