<?php
/**
 * @author Rebeca Martínez García
 * @copyright  Copyright © 2018  Discover Barcelona
 */

// @codingStandardsIgnoreFile

/**
 * @var \Magento\Theme\Block\Html\Header\Logo $block
 */
?>
<?php $storeName = $block->getThemeName() ? $block->getThemeName() : $block->getLogoAlt(); ?>
<span data-action="toggle-nav" class="action nav-toggle"><span><?= /* @escapeNotVerified */
        __('Toggle Nav') ?></span></span>
<?php if ($block->isHomePage()): ?>
    <strong class="logo">
        <?php else: ?>
        <a class="logo" href="<?= $block->getUrl('') ?>" title="<?= /* @escapeNotVerified */
        $storeName ?>">
            <?php endif ?>
            <img class="logo-img" src="<?= /* @escapeNotVerified */
            $block->getLogoSrc() ?>"
                 alt="<?= /* @escapeNotVerified */
                 $block->getLogoAlt() ?>"
            />
            <?php if ($block->isHomePage()): ?>
    </strong>
<?php else: ?>
    </a>
<?php endif ?>

