<?php
/** @var  \Dbtours\Catalog\Block\Product\View\Options\Type\TourEvent $block */
$showTime           = $block->getTimeFormat() ? "showsTime: true," : "showsTime: false,";
$timeFormat         = $block->getTimeFormat() ? "timeFormat: '" . $block->getTimeFormat() . "'," : "";
$calendarYearsRange = $block->getYearsRange() ? "yearRange: '" . $block->getYearsRange() . "'," : "";
?>

<!-- TODO use styles css -->
<div class="container-ajax-loader">
    <div class="ajax-loader"></div>
</div>

<div id="div-<?= $block->getId()?>">

</div>

<div id="container-accordion"></div>

<script type="text/javascript">
    require(["jquery", "mage/calendar", "accordion"], function($){
        function showOptions(options, languagesData) {
            var html = '<div id="language-accordion">';
            for (var language in options) {
                html += '<div data-role="collapsible" class="option-header"> <div data-role="trigger"><a>'
                    +languagesData[language]+
                    '</a></div></div>';
                html += '<div data-role="content" class="option-content"><div class="option-content-elements">';
                html += '<input class="language-option" id="language-' + language +'"' +
                    'type="radio" ' +
                    'name="<?= $block->getName()?>[language_code]" ' +
                    'value="' + language +'">';
                for (var time in options[language]) {
                    var tourEventId = options[language][time];
                    html += '<input class="time-option" ' +
                        'id="' + tourEventId+language + '" ' +
                        'data-language="' + language + '" ' +
                        'type="radio" ' +
                        'name="<?= $block->getName()?>[tour_event_id]" ';
                    if (tourEventId > 0) {
                        html +='value="' + tourEventId +'">';
                        html += '<label for="' + tourEventId+language +'">' + time + '</label>';
                    } else {
                        html += 'disabled>';
                        html += '<label for="' + tourEventId+language +'" class="disabled">' + time + '</label>';
                    }

                }
                html += '</div></div>';
            }
            html += '</div>';
            $("#container-accordion").html(html);
            $("#language-accordion").accordion();
            $('input.time-option:radio').click(function(e) {
                // reset selected language
                $('input.language-option:radio').attr('checked',false);
                 //mark as checked current language
                var selectedLanguage = $(this).data("language");
                $("#language-" + selectedLanguage).attr('checked', true);
            });
        }
        function initDatepicker(data) {
            $(<?= "'#div-" . $block->getId() . "'"?>).datepicker({
                <?= $showTime ?>
                <?= $timeFormat ?>
                <?= $calendarYearsRange ?>
                showButtonPanel: true,
                showOtherMonths: true,
                selectOtherMonths: true,
                minDate: new Date(),
                firstDay: 1,
                changeMonth: true,
                changeYear: true,
                dateFormat: "<?= $block->getDateFormat() ?>",
                buttonImage: "<?= $block->getImage() ?>",
                beforeShowDay: function (date) {
                    var string = jQuery.datepicker.formatDate('yy-mm-dd', date);
                    return [data.dates.indexOf(string) != -1];
                },
                onSelect: function(dateText, inst) {
                    var date = new Date(Date.parse($(this).datepicker('getDate')));
                    var dateFormatted = jQuery.datepicker.formatDate('yy-mm-dd', date);
                    if (data.dates.indexOf(dateFormatted) != -1) {
                        showOptions(data.options[dateFormatted], data.languages);
                    }
                }
            });
        }

        $.ajax({
            url : "<?= $block->getDataUrl() ?>",
            type : 'GET',
            data : {
                'productId' : "<?= $block->getProductId() ?>",
            },
            dataType:'json',
            success : function(data) {
                if(data.dates) {
                    initDatepicker(data);
                    $(".container-ajax-loader").css("display","none");
                }
            },
            error : function(request,error)
            {
                alert("An error occurs, please refresh the current page");
            }
        });
    });
</script>

